### PR TITLE
Cirumvent OSX errors

### PR DESCRIPTION
**Pull request by alexg9010**
- zcat on osx adds an ".Z" -extension prior to extraction
- internally zcat is a call of "gunzip -c"

### CODE REVIEW

**Comment by alexg9010** [comment]
@al2na Those pull requests contain the fixes for the methCall segmentation fault. 
Right now I do not know why the travis checks do not pass, but it is somehow related to installing  genomation from source.

**Comment by al2na** [comment]
can you troubleshoot with genomation maintainers ? does genomation devel
version pass checks on BioC?

**Comment by alexg9010** [comment]
The builds all pass on BioC.

**Comment by al2na** [comment]
ok, I will merge it soon. Thank you!

**Comment by ccwang002** [comment]
I tried but failed to build the pull request version locally with the following error.

```
Error in .install_package_code_files(".", instdir) : 
files in '/Users/liang/tools/methylKit/R' missing from 'Collate' field:
  onUnload.R
```

I found that one may need to add the newly created file `onUnload.R` to `DESCRIPTION`:

```
Collate:
    'methylKit.R'
    'backbone.R'
    ...
    'onUnload.R'
```

to correctly build the package and pass all tests locally.

By the way, when I re-generated the documentation by `devtools::document()`, I spotted many changes in the documents. One may like to re-generate all docs and include those changes in the source code.

Thanks!

**Comment by alexg9010** [comment]
I added onUnload.R to collate and R CMD Check went through without errors.

**Comment by al2na** [comment]
@alexg9010 genomation installation is a problem I think. Is it something you can fix, it seems to be related to the C part? maybe we can remove that dependency since Rsamtools provides same functionality now?

**Pull request closed without merging**
