### PR TITLE
Integrate MethylDBClasses and methods

### PR DESCRIPTION
**Pull request by alexg9010**
Hey Altuna,

hopefully you don't suffer from reading this bunch of code.  All in all I think the new classes and methods will help a lot in dealing with larger data sizes!

There is one change, concerning the regionCounts methods that I also have commented on. Its basically that the regions returned by the function will always be sorted, even though the input was not. I hope this won't be to fatal. 

If you have any questions concerning the implementation, don't hesitate to ask!

Best,
Alex

### CODE REVIEW

**Comment by al2na** [comment]
thanks Alex!!! Do you have any idea why the tests fail ?

**Comment by alexg9010** [comment]
i will check it!

**Comment by alexg9010** [comment]
The Problem was that the methylDB objects that were saved as data had my private path to their database included, such that loading them on any other system will fail.

**Comment by alexg9010** [comment]
There are now two files methylDBClasses.R and methylDBFunctions.R that include the Class definitions + accessor-/coercion- methods  and collected methods from all other files. 
The function documentations inside tabix.functions.R are created, but where added to .Rbuildignore, so that they should not show up in reference manual.

**Comment by al2na** [comment]
Thanks Alex!! It passes the check

**Pull request merged**
